class OoHauntedHouse
  def initialize
    new Room("SE", "Dark Corner")
    new Room("WE", "Overgrown Garden")
    new Room("SWE", "By a Large Wood Pile")
    new Room("WE", "Yard by Rubbish")
    new Room("WE", "Weed Patch")
    new Room("SWE", "Forest")
    new Room("WS", "Thick Forest")

    new Room("NS", "Blasted Tree")
    new Room("SE", "Corner of the House")
    new Room("WE", "Entrance to the Kitchen")
    new Room("NW", "Kitchen and Grimy Cooker")
    new Room("SE", "Scullery Door")
    new Room("W", "Room with Inches of Dust")
    new Room("NE", "Rear Turret Room")
    new Room("NSW", "Clearing by House")

    new Room("NS", "Path")
    new Room("NS", "Side of the House")
    new Room("SE", "Back of the Hallway")
    new Room("WE", "Dark Alcove")
    new Room("NWUD", "Small Dark Room")
    new Room("SE", "Bottom of a Spiral Staircase")
    new Room("WSUD" , "Wide Passage")
    new Room("NS", "Slippery Steps")

    new Room("N", "Clifftop")
    new Room("NS", "Near a Crumbling Wall")
    new Room("NSE", "Gloomy Passage")
    new Room("WE", "Pool of Light")
    new Room("WE", "Impressive Vaulted Hallway")
    new Room("NSW", "Hall by a Thick Wooden Doors")
    new Room("NS", "Trophy Room")
    new Room("NS", "Cellar with Barred Window")

    new Room("S", "Cliff Path")
    new Room("NSE", "Cupboard with Hanging Coat")
    new Room("NSW", "Front Hall")
    new Room("S", "Sitting Room")
    new Room("NSUD", "Steep Marble Stairs")
    new Room("N", "Dining Room")
    new Room("N", "Deep Cellar with a Coffin")
    new Room("NS", "Cliff Path")

    new Room("NE", "Closet")
    new Room("NW", "Front Lobby")
    new Room("NE", "Library of Evil Books")
    new Room("W", "Study with a Desk and Hole in the Wall")
    new Room("NSE", "Weird Cobwebby Room")
    new Room("WE", "Very Cold Chamber")
    new Room("W", "Spooky Room")
    new Room("NS", "Cliff Path by the Marsh")

    new Room("SE", "Rubble-Strewn Verandah")
    new Room("NSW", "Front Porch")
    new Room("E", "Front Tower")
    new Room("WE", "Sloping Corridor")
    new Room("NW", "Upper Gallery")
    new Room("S", "Marsh by a Wall")
    new Room("SW", "Marsh")
    new Room("NW", "Soggy Path")

    new Room("NE", "By a Twisted Railing")
    new Room("NWE", "Path through an Iron Gate")
    new Room("WE", "By Railings")
    new Room("WE", "Beneath the Front Tower")
    new Room("WE", "Debris from Crumbling Facade")
    new Room("NWE", "Large Fallen Brick Work")
    new Room("NWE", "Rotting Stone Arch")
    new Room("W", "Crumbling Clifftop")
  end
end