module Oo
  module Things
    AXE = :AXE
    SHOVEL = :SHOVEL
    ROPE = :ROPE
    MATCHES = :MATCHES
    SCROLL = :SCROLL
    COINS = :COINS
    VACUUM = :VACUUM
    BATTERIES = :BATTERIES
    STATUE = :STATUE
    KEY = :KEY
    MAGIC_SPELLS = :MAGIC_SPELLS
    RING = :RING
    CANDLESTICK = :CANDLESTICK
    CANDLE = :CANDLE
    PAINTING = :PAINTING
    BOAT = :BOAT
    GOBLET = :GOBLET
    AEROSOL = :AEROSOL
  end
end
